### ISSUE TITLE
usb examples don't build out of box. Need tons of path fixing for default install of mplabx and harmony

### ISSUE THREAD

**Issue by studleylee** [Microchip-MPLAB-Harmony/usb#1]
usb examples don't build out of box. Need tons of path fixing for default install of mplabx and harmony

**Comment by zzelevl** [comment]
All applications in Harmony v3 are self-contained and don't require any include path setup to any Harmony components outside of application folder, and as such, all applications build straight out of the box.
If you can provide more specifics on your problem, we can look at it, but in general, if you have latest MPLAB X 3.15 and XC32 v2.15 installed, and you clone usb repo, all applications in the usb/apps folder will build out of box.

**Comment by studleylee** [comment]
I'll write jira C08955
