### ISSUE TITLE
Help file Documentation issue

### ISSUE THREAD

**Issue by joemdiente** [Microchip-MPLAB-Harmony/usb#16]
![image](https://user-images.githubusercontent.com/11147484/127091998-960f5a7b-fc30-4d7b-9e99-b606d75085da.png)
On page 2 of the usb help file, it mentions EHCI complaint instead of compliant.
See attached picture above.

Thanks

**Comment by joemdiente** [comment]
![image](https://user-images.githubusercontent.com/11147484/127426755-1073fce3-3262-4e6c-845f-66345c55d504.png)
Another documentation issue.

**Comment by joemdiente** [comment]
Just dumping feedbacks regarding documentation here, 
![image](https://user-images.githubusercontent.com/11147484/128053684-03d273d2-207a-4dd5-8e2f-17d8488e9dbc.png)
Thank you.

**Comment by shijas-mayan** [comment]
@joemdiente,  These issues are resolved in the USB v3.8.1 release.

**Comment by joemdiente** [comment]
Thanks @shijas-mayan
