### ISSUE TITLE
USB HOST AUDIO with PIC32MX270F256B-50I/SP

### ISSUE THREAD

**Issue by ytsnew** [Microchip-MPLAB-Harmony/usb#3]
Please visit
https://www.microchip.com/forums/m1109359.aspx

**Comment by JPortici** [comment]
Just wanted to add: Also present on target mcu PIC32MK1024GPE100

**Comment by shijasm** [comment]
> Please visit
> https://www.microchip.com/forums/m1109359.aspx

This is fixed in USB v3.4.0
